version: '2'
services:
  start:
    build: .
    image: merge-pdfs
    command: /bin/bash
    ports:
    - "9232:9232"
    volumes:
    - ./test:/home/test
    - ./index.js:/home/index.js
    - ./package.json:/home/package.json
    mem_limit: 1028m
    restart: always